
ssh root@k8s-master "mkdir -p /home/kevin"
ssh root@k8s-node01 "mkdir -p /home/kevin"
ssh root@k8s-node02 "mkdir -p /home/kevin"
ssh root@k8s-node03 "mkdir -p /home/kevin"
ssh root@k8s-node04 "mkdir -p /home/kevin"
ssh root@k8s-node05 "mkdir -p /home/kevin"

ssh root@k8s-master "mkdir -p /home/kevin/git"
ssh root@k8s-node01 "mkdir -p /home/kevin/git"
ssh root@k8s-node02 "mkdir -p /home/kevin/git"
ssh root@k8s-node03 "mkdir -p /home/kevin/git"
ssh root@k8s-node04 "mkdir -p /home/kevin/git"
ssh root@k8s-node05 "mkdir -p /home/kevin/git"

ssh root@k8s-master "mkdir -p /home/kevin/git/lwdee"
ssh root@k8s-node01 "mkdir -p /home/kevin/git/lwdee"
ssh root@k8s-node02 "mkdir -p /home/kevin/git/lwdee"
ssh root@k8s-node03 "mkdir -p /home/kevin/git/lwdee"
ssh root@k8s-node04 "mkdir -p /home/kevin/git/lwdee"
ssh root@k8s-node05 "mkdir -p /home/kevin/git/lwdee"

ssh root@k8s-master "mkdir -p /home/kevin/git/lwdee/build"
ssh root@k8s-node01 "mkdir -p /home/kevin/git/lwdee/build"
ssh root@k8s-node02 "mkdir -p /home/kevin/git/lwdee/build"
ssh root@k8s-node03 "mkdir -p /home/kevin/git/lwdee/build"
ssh root@k8s-node04 "mkdir -p /home/kevin/git/lwdee/build"
ssh root@k8s-node05 "mkdir -p /home/kevin/git/lwdee/build"

ssh root@k8s-master "mkdir -p /home/kevin/git/lwdee/config"
ssh root@k8s-node01 "mkdir -p /home/kevin/git/lwdee/config"
ssh root@k8s-node02 "mkdir -p /home/kevin/git/lwdee/config"
ssh root@k8s-node03 "mkdir -p /home/kevin/git/lwdee/config"
ssh root@k8s-node04 "mkdir -p /home/kevin/git/lwdee/config"
ssh root@k8s-node05 "mkdir -p /home/kevin/git/lwdee/config"

ssh root@k8s-master "mkdir -p /home/kevin/git/lwdee/data"
ssh root@k8s-node01 "mkdir -p /home/kevin/git/lwdee/data"
ssh root@k8s-node02 "mkdir -p /home/kevin/git/lwdee/data"
ssh root@k8s-node03 "mkdir -p /home/kevin/git/lwdee/data"
ssh root@k8s-node04 "mkdir -p /home/kevin/git/lwdee/data"
ssh root@k8s-node05 "mkdir -p /home/kevin/git/lwdee/data"

ssh root@k8s-master "mkdir -p /home/kevin/git/lwdee/log"
ssh root@k8s-node01 "mkdir -p /home/kevin/git/lwdee/log"
ssh root@k8s-node02 "mkdir -p /home/kevin/git/lwdee/log"
ssh root@k8s-node03 "mkdir -p /home/kevin/git/lwdee/log"
ssh root@k8s-node04 "mkdir -p /home/kevin/git/lwdee/log"
ssh root@k8s-node05 "mkdir -p /home/kevin/git/lwdee/log"


